### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by AndrewBelt** [AScustomWorks/AS#1]
Speaking mostly for the sake of others, you should collect all used source licenses into the LICENSE.txt file which is distributed with the binary, so people know the licenses of the source works. Example:

```
### Fundamental ###

<paste Fundamental's LICENSE.txt here>

### HetrickCV ###

<paste HetrickCV's LICENSE.txt here>

...
```

**Comment by AScustomWorks** [comment]
Right, I'll fix that asap ;)

**Comment by AScustomWorks** [comment]
Update: only v0.5.0 releases had the old license file, now those releases are deleted, and new releases have the proper source licenses added into the LICENSE.txt

**Comment by AndrewBelt** [comment]
Cool! The only thing: I wrote Fundamental, not Mark Borgerding. https://github.com/VCVRack/Fundamental/blob/master/LICENSE.txt

**Comment by AScustomWorks** [comment]
I think I got that license and name text from an old Fundamental license, not sure but is corrected now everywhere, including on the release zip files ;)

**Comment by AndrewBelt** [comment]
I think you took it from the kissfft license from LICENSE-dist.txt :)
