### ISSUE TITLE
Can't add VU meters

### ISSUE THREAD

**Issue by zezic** [AScustomWorks/AS#12]
After trying to add `Mono VU meter` or `Stereo VU meter` to my rack I got nothing. Console is quiet.
I'm on Linux and my Rack is built from unstable `master` branch (0.6).

Does it work for you? Can you hint me on how can I investigate this problem myself?

Thank you a lot for such nice modules collection!

**Comment by AScustomWorks** [comment]
Not sure what could it be, just tested on Mac with today's v0.6 rack, also tested on VM with linux ubuntu (older v0.6 rack version) both loading fine:
![vu-linux](https://user-images.githubusercontent.com/34798768/37886672-05051722-307a-11e8-8f20-9b92ba15972d.jpg)
![vu](https://user-images.githubusercontent.com/34798768/37886673-05195c5a-307a-11e8-9b6f-7787626b262c.jpg)

**Comment by zezic** [comment]
OK, thank you. Then it's case related to my system. I'm a now familiar enough with modules programming so, I think, I can fix it myself soon.

**Comment by zezic** [comment]
I just checked dBiz modules - meters in mixer works normally.
I think, I'll narrow down the problem by disabling parts of code, fix it myself soon and make PR.

**Comment by AScustomWorks** [comment]
Hi again, found the error(a silly one): name of the svg files for both modules had to start with Uppercase, make a git checkout and pull, or just change the case on your local copy ;)

**Comment by zezic** [comment]
Huh, right, it works now. Thanks!
