### ISSUE TITLE
Non appearance of two modules in v 0.6 [Linux]

### ISSUE THREAD

**Issue by ZuluEchoRomeOscar** [AScustomWorks/AS#14]
The two being Mono & Stereo VU Meters.

**Comment by ZuluEchoRomeOscar** [comment]
See here for possible solution:
https://github.com/sebastien-bouffier/Bidoo/issues/68#issuecomment-377073588

**Comment by AScustomWorks** [comment]
Please check closed issues before opening a repeated and already fixed one.
