### ISSUE TITLE
Tiny patch for vu meter testing

### ISSUE THREAD

**Issue by aebrouse** [AScustomWorks/AS#16]
[tiny vu meter test patch.zip](https://github.com/AScustomWorks/AS/files/1867145/tiny.vu.meter.test.patch.zip)  
okay here is the smallest patch I can make that will trigger the issues .  seems if I strip everything out but the mixer tinysine and the vu meters.. active or inactive  the problem shows up with 6 meters and goes away  like a reverb or delay back to no clicking  when I drop to 5 meters in the rack.

**Comment by AScustomWorks** [comment]
Tested this patch too, it worked fine so... I can't reproduce the error. I even complicated things a little bit:

![vus](https://user-images.githubusercontent.com/34798768/38259984-0d8c280a-372c-11e8-9645-5da4849e0bba.jpg)

 Now, Andrew says audio processing and graphic processing run on separate threads but I'm suspecting that somehow the graphic side is taking a toll on your particular computer/processor/graphic card combo, and well, you computer is not precisely new ;)

I'll keep looking into this but as I can't reproduce the glitches my recommendation for now is to try to not use the VU meters all over the place.

I know they give a nice visual feedback, but mostly VU meters are just eye candy when used like you are doing, on the lfo signal path for example as it probably won't be saturated at any point, and that's the main goal of a VU meter, to check for saturated levels.

So if you need a visual input to see what's going on, maybe ML volt meter module is best in your case?

**Comment by aebrouse** [comment]
Thanks, Freddy.. yeah I liked the eye candy but can work without it .. has me curious if the Nsynthi meters  would give me issue.. oh well not a MAJOR issue glad we could make certain of THAT 😊

________________________________

**Comment by AScustomWorks** [comment]
Oh, good idea about testing with Nysthi meters, he probably made his own implementation (I'm using vcv rack own method).

Now you got me thinking, maybe adding a bypass switch to the meters could be useful, so you can set them off without having to rewire everything.

**Comment by AScustomWorks** [comment]
I'll take a look to see if it can be restricted to lower frame refresh ;)
