### ISSUE TITLE
Triggers Mk1 and MK2  - possible feature request and/or question

### ISSUE THREAD

**Issue by JeffGreenlee42** [AScustomWorks/AS#17]
Hi,  

I have a question that *might* be a feature request if doing so is possible without major effort:  

I really like  your Trigger modules.  But one thing that I can't help think of when I use them is this:   Why limit the trigger labels to the finite set you have defined?   Is there a reason why there could not be a "custom"  category that would allow a user to type in their own value for a given trigger?   Obviously this would in the Real Eurorack world this would not work,  but for a virtual module, such an option seems trivial.  I am imagining that the ability define and customize the displayed label text might be quite helpful - especially in a live performance, or for helping to logically organize event triggers. 

My question is:  is there a development limitation that prevents this?  or is this an aesthetic choice?

**Comment by AScustomWorks** [comment]
Hi,
Actually not so trivial, and there's a reason to keep it like it this, look [here](https://github.com/AScustomWorks/AS/issues/10)
