### ISSUE TITLE
A-B-Y Switch 

### ISSUE THREAD

**Issue by Cordoha** [AScustomWorks/AS#18]
The A-B-Y Switch module doesn't display in Ubuntu 16.04.

**Comment by AScustomWorks** [comment]
HI Cordoba, my bad, I keep forgetting about Linux case sensitive file names.
 I'll correct it asap on the distributed plugins, meanwhile you can fix it yourself just by renaming one file:
Go to the plugin folder, open the res folder and find the file ABY.svg, change the name to aBy.svg and all should be fine the next time you try to load this module.

**Comment by Cordoha** [comment]
Hey man, thanks for the reply. That fixed it. Awespme plugins.
Cheers.
