### ISSUE TITLE
Feature Request: Kill Gate Soft cut off 

### ISSUE THREAD

**Issue by BillScherer** [AScustomWorks/AS#19]
Kill Gate is super handy, but I have to add a slew limiter most of the time to quell the hard cut off, otherwise there is an audible snap at cut-off.  Is there a better way to do this? Or could a switch be added to Kill Gate to enable a soft cut off?

Thanks!

**Comment by AScustomWorks** [comment]
Hi Bill, question:

You are using KillGate with audio signals, right?
As with the related modules, is meant to work with trigger and gate signals where the abrupt cut is not a problem, and even desired.

While I'd do audio cuts in a mixer module and it's cv volume inputs, I can see how a soft switch could be useful to have in the module. I'll look into that.

**Comment by BillScherer** [comment]
Thanks!

**Comment by AScustomWorks** [comment]
Hi again Bill, soft cut/mute is included now in Launch Gate, Kill Gate and Flow modules in v0.6.5.

It turned out to be a great feature in Flow module in particular, I'll make a video showing a good use of it ;)
