### ISSUE TITLE
8 stage sequencer

### ISSUE THREAD

**Issue by alto777** [AScustomWorks/AS#23]
hi Alfredo!

I needed a 8 sequencer and happened to grab your variant. In the Fundamental SEQ-3 the "STEPS" knob is snappy, allowing easy selection of 1 to 8 steps, but in yours the knob is not. Is this a design choice, if so, what is the thinking?

alto777

**Comment by AScustomWorks** [comment]
Hi Alto!
As you can see on the front page, it is based on Autodafe's and Fundamental's SEQS so one of them made that decision before me hehe (SEQ-3 steps knob had no snap back then so I guess it started there).

I'll give my input based on what I know now:

Doing it one way or the other should be of no consequence actually, as long as the code takes care of reading the parameter accurately, but it definitely is more easy to use a snap knob.
That being said, I can't see me using a snap on TriggersMKII label knob for example :)
If anything, the snap knob gives the user a little feedback so it seems like a good idea to use it whenever it makes sense.

Btw, the latest version of SEQ-3 has more optimized code so you may want to stick with that one and take just what you think is useful from my version.

**Comment by alto777** [comment]
Makes sense, thanks. I see you dropped the 8 sequencer from your lineup anyway, of course the 16 can act like the 8 and there's always room in the rack… and with the digital displays you've now added dialing in a number is easy enough.

a7
