### ISSUE TITLE
phaserfx issue

### ISSUE THREAD

**Issue by phlexmaster** [AScustomWorks/AS#30]
Hi, 

I found the following issue with the PhaserFX  0.6.8 in VCV:

- 1st instance (middle row) bassline with the phaserfx as the final effect before going to the mixer.
- 2nd instance (bottom row) created where a pad uses a second phaser as end effect too before mixing.
- issue: the second phaser starts to play the bassline once the depth knob is turned up, even though nothing is connected to the in (bottom row phaser shows output light on the out).
- when connecting up the pad audio and turning up the the depth knob, the output of the phaser is a mix of the pad and the bassline
- tried both copying as picking a new instance of the phaserfx, both same issue. tried disconnecting cables and initializing the instance, both same problem.

I am not a programmer, but it seems like the second phaser shares an audio input variable with the first one, that becomes active when the depth knob is turned up.

![image](https://user-images.githubusercontent.com/41327428/42811820-ac138ebc-89b3-11e8-97a2-af8b2e515ca1.png)

**Comment by AScustomWorks** [comment]
Hi plexmaster, I can reproduce this bug, really weird one as every available module is supposed to be isolated from everything else until connected. I'll see if I can find the cause, thanks a lot for reporting this.

**Comment by jedgarpark** [comment]
I ran into this as well -- created two Phaser FX modules and the second one seems to take over the rate for both of them.

**Comment by AScustomWorks** [comment]
fixed
