### ISSUE TITLE
Request: Reverse Lighting Pattern on Flow

### ISSUE THREAD

**Issue by jonheal** [AScustomWorks/AS#31]
Maybe it's just me, but it would make more sense to me if the big buttons light up red when signal is **flowing**, rather than when it's not. Otherwise, LOVE your stuff!

**Comment by AScustomWorks** [comment]
Hi jonheal, thanks for the feedback! I get what you are saying (fundamental mutes module works like that), but the logic I went with for all my modules is this:
Any switch light, no matter what the function it controls does, should be ON to indicate the function is active.
In Flow case the inactive state of the module is to let the signal pass thru, so it goes ON when the mute function is active.

I'll check if it's possible to add a switch to reverse this behavior so everybody is happy ;)

**Comment by AScustomWorks** [comment]
The switch is added in v0.6.9
