### ISSUE TITLE
TinySine tuning reference

### ISSUE THREAD

**Issue by ValleyAudio** [AScustomWorks/AS#32]
Was TinySine supposed to be tuned to A4 at 0V? Most other oscillators are tuned to C4

**Comment by MarcBoule** [comment]
Indeed, according to:
https://vcvrack.com/manual/VoltageStandards.html#pitch-and-frequencies
0V should ideally be C4 (“middle C”, MIDI note 60, f0= 261.626 Hz)

**Comment by AScustomWorks** [comment]
Hi guys!
I wonder how that happened... any ideas about how to fix it?

**Comment by AScustomWorks** [comment]
I was thinking about adding a switch for A or C tuning, with A being the default.
This way the switch itself saves the user selection, quick and dirty fix... but I'm more intrigued about setting the proper tuning hehe.
I believe this happened when I changed  the sine variable calculation method(to get a proper sine output when looking the signal on the scope), not that I knew what I was doing :).

'''
	float sine = sinf(2.0f * M_PI * (phase+1 * 0.125f)) * 5.0f;
	//original sine
	//float sine = sinf(2 * M_PI * phase)+ sinf(2 * M_PI * phase * 2)*5;
'''

**Comment by AScustomWorks** [comment]
This issue was resolved already, closing the thread ;)
