### ISSUE TITLE
Multi 2x5 feature request

### ISSUE THREAD

**Issue by MarcBoule** [AScustomWorks/AS#35]
Hi Alfredo,
In Multi 2x5, when the 2nd input at the top right is unconnected, it could perhaps automatically use the first input's signal, thus becoming a 1x10 Multi, and all for free :-)
Cheers!
Marc

**Comment by AScustomWorks** [comment]
Hi Marc, nice and easy idea, I'll do it ;)

**Comment by AScustomWorks** [comment]
Update for Multi 2x5(and a couple more goodies) is up and waiting on the repo.

**Comment by MarcBoule** [comment]
Cool! Thanks Alfredo :-)
