### ISSUE TITLE
8CH and 4CH Mixer 0.6.13

### ISSUE THREAD

**Issue by therealkitman** [AScustomWorks/AS#36]
Hi. Having issues making sense of the mixer's resultant levels. If I inject a 1 volt signal into channel 1, the left and right outputs are 0.71V each when all mixers are at full level and the output channel is 1.41V. See pic.

![image](https://user-images.githubusercontent.com/14888092/51906576-5e76fe00-23ff-11e9-9a4d-ce9cfd30b02e.png)

If I pan hard left, the both left and right channels are affected: shuouldn't the left channel be unaffected? Also the Channel 1 output is affected by the panning too. See pic.

![image](https://user-images.githubusercontent.com/14888092/51906759-d513fb80-23ff-11e9-83bd-836d72012d6b.png)

I can't follow the logic as to what is happening. Am I misunderstanding how this mixer works?

I also noticed that if the left channel Mix In is used without a right channel (open input) it does not get added to the mix.

**Comment by AScustomWorks** [comment]
Hi therealkitman, I meant to respond but totally forgot about your post, sorry.

The current pan behavior has to do with the fact that the channels are treated like "stereo pairs" (and each channel output is summing the results of both "pairs"), maybe this should be changed?

About the Mix IN, it's the original intended behavior so both left and right inputs are forced to be connected, I guess I can switch it to act as L/mono(L goes to both L & R) and L/R (separated signals).

**Comment by therealkitman** [comment]
HI Freddy, Thanks for the reply. I understand how/why what it's doing now with your explanation. I'm new to this and was just comparing this mixer against others. I'll close this issue and let you decide if anything needs to be changed.
Regards.
