### ISSUE TITLE
ReScale 0.6.13

### ISSUE THREAD

**Issue by therealkitman** [AScustomWorks/AS#37]
Hi,
found a quirk with ReScale. With the 0V/5V input and 0V/10V output (Switch 4), the output voltage does not drop below 5V. Looks like an offset is used instead of a scaling issue? See pic.

![image](https://user-images.githubusercontent.com/14888092/52909017-c1034180-32bb-11e9-8bce-d6c28f1c6cbe.png)
Regards...

**Comment by AScustomWorks** [comment]
Hi therealkitman, the option 4 on the switch is intended to be used with 1V/OCT input only, and it scales whatever voltage you send to it to 1V/OCT(it cycles to cover one octave):

ReScale

Utility module to convert from one voltage range to another, available inputs are: -5v/5v, 0v/5v, 0v/10v, 1V/OCT*. Available output signal options are: -5v/5v, 0v/5v, -10v/10v, 0v/10v* *1V/OCT option is to convert any voltage source to 1 octave 1V/OCT range.
![rescale-1voct](https://user-images.githubusercontent.com/34798768/52918163-c790b980-32b9-11e9-8209-d0953045d126.jpg)

**Comment by therealkitman** [comment]
Ah ha! I thought option 4 was for all inputs with the 1V/Oct a special case. Ok, option 4 is exclusively for 1V/Oct input only.
Thanks.
