### ISSUE TITLE
feature request: white version gui

### ISSUE THREAD

**Issue by ghost** [AScustomWorks/AS#38]
This would be nice perhaps both white and metallic black versions to match other modules.  Your plugins are the best.

**Comment by AScustomWorks** [comment]
Hi modman2019, thanks ;)
Haven't gone that way yet as right now the skins are a bit of a hack, and don't want to get into troubles because of the high modules count on this plugin, but I'll see if it's feasible/easier when V1 goes public.

**Comment by modman2019** [comment]
No worries on it. They work that’s what matters 😊

**Comment by AScustomWorks** [comment]
VCV Rack is at V2 and still no official way to support skins, so I'll close this request (will update if something changes in the future)
