### ISSUE TITLE
Right-Clicking Rate Knobs on Delay Plus Stereo FX Does Not Set Default Timing

### ISSUE THREAD

**Issue by jonheal** [AScustomWorks/AS#39]
Right-Clicking Rate Knobs on Delay Plus Stereo FX Does Not Set Default Timing

**Comment by AScustomWorks** [comment]
Hi Jon, which version of Rack are you using? I haven't made the update to v1.0 yet.

**Comment by jonheal** [comment]
0.6.2c on Windows.

**Comment by AScustomWorks** [comment]
Hi Jon, is this still happening? I did review the code, but nothing really obvious there, and it's actually handled directly by Rack, unless the code overrides the default behavior (not doing that here).
