### ISSUE TITLE
BPM Clock (AS v0.5.3): RST button having strange behavior...

### ISSUE THREAD

**Issue by DomiKamu** [AScustomWorks/AS#4]
Hi,

As indicated in title, the **BMP Clock** module having a strange behavior when I use its RST button: all sequencers behind (with correctly wired CLOCK and RESET) they restart at first step (it's the main goal), but then run very quickly while the RST button is hold (seqs run at correct speed when this button is released, however).

I have tested with VCV's Pulse Matrix 16, Autodafe's 16-Step Sequencer, cf's trSeq and... your step sequencer. Same behavior.

Hope mine explanations are clear.

Regards.
Dominique.

**Comment by AScustomWorks** [comment]
Thanks Dominique!, The reset button issue is corrected now and will appear on the next release version (0.5.4)
