### ISSUE TITLE
Rack v1: invalid tags in plugin.json

### ISSUE THREAD

**Issue by cschol** [AScustomWorks/AS#41]
The manifest validator found invalid tags in the `plugin.json`:

```
Validating AS
TriLFO: invalid tags: Triple
TriggersMKI: invalid tags: Trigger
TriggersMKII: invalid tags: Trigger
TriggersMKIII: invalid tags: Trigger
SuperDriveFx: invalid tags: Overdrive
TremoloFx: invalid tags: Tremolo
TremoloStereoFx: invalid tags: Tremolo, Stereo
```

The list of valid tags is defined here: https://github.com/VCVRack/Rack/blob/v1/src/plugin.cpp#L534

**Comment by AScustomWorks** [comment]
Sorry, forgot to remove  those tags, fixed now: https://github.com/AScustomWorks/AS/commit/8ece883c274eaf37068d22dbe8ade7c422d38aae

Any chance to add "Overdrive" and "Tremolo" to the valid tags list?

**Comment by cschol** [comment]
Thanks. Put in a feature request with Andrew in the Rack repo.
