### ISSUE TITLE
GUI: Inconsistent visual treatment on ports

### ISSUE THREAD

**Issue by claymill** [AScustomWorks/AS#43]
This is not a major issue, but several AS modules don't follow the industry standard visual differentiation between in and out ports. Some, like QuadVCA/Mixer, do follow the standard with a box around only the out ports, but others, like the 2, 4, and 8-channel mixers, have a box around some of the inputs as well as the outputs, which can be a little confusing.

Would be happy to dig into the SVGs and make a PR for this!

**Comment by AScustomWorks** [comment]
Hi Clayton, I didn't noticed I had forgotten to include the "O" on the individual output label box on 2 and 4 mixers, I'll fix that.

For all the modules the design decision on labels, boxes, etc. was made according to the available space on each module and considering this goals:
- Modules being as small as possible
- Panel design being as clean and minimal as possible across all my plugins, free and paid.
Sometimes is just impossible to adhere to a standard, and there's not really one in place for that matter ;).

That being said, and with this factors in consideration, please mark the modules that you think could be improved(if you can provide an example on one of the difficult modules even better) and I'll give it a second thought.
![AS-free](https://user-images.githubusercontent.com/34798768/59971250-f1930a80-953d-11e9-8c86-8b3687bf05a7.jpg)
![AS-paid](https://user-images.githubusercontent.com/34798768/59971260-0f606f80-953e-11e9-8db2-dda120e6e06d.jpg)

**Comment by claymill** [comment]
Glad to help! I put together a few examples with corresponding mockups of how they would look with the input/output backgrounds made consistent.

![AS inputs-outputs](https://user-images.githubusercontent.com/1455432/59979516-92211300-95ae-11e9-8b9b-fe721f9ceaab.png)

**Comment by AScustomWorks** [comment]
Thanks!
Indeed it's better to have the box "mark" on each output port, but the design rules should be consistent thru all the modules:
- In the case of Steps is just not possible, the box only fits if made smaller than the others.
- ZCV2T does work fine because the height of the box is the same as on the other boxes.

But you got me thinking again about this, I'll try a different approach and see if it can work everywhere ;)

**Comment by AScustomWorks** [comment]
I think this can be the simplest way to solve the issue (box removed on inputs, gold port for the outputs + box mark whenever possible to include it without looking weird):
![AS-free-graphics-update](https://user-images.githubusercontent.com/34798768/59981351-97d72280-95c7-11e9-9809-892ba53a2b58.jpg)

**Comment by claymill** [comment]
That looks like a good solution! It's much easier to quickly tell where the outputs are now. I wonder, do you need the box mark at all with the gold ports? It would let you further visually simplify the panels.

Either way, this is a big usability improvement.

**Comment by AScustomWorks** [comment]
I tried without the boxes, but looks confusing... instead added a few more boxes hehe:
![AS-free-graphics-update](https://user-images.githubusercontent.com/34798768/59983613-7f770000-95e7-11e9-8f5b-6b30f8fb698e.jpg)

**Comment by AScustomWorks** [comment]
Source code updated now, should be available on Rack soon ;)
