### ISSUE TITLE
Phaser FX creates "mix" when more than one

### ISSUE THREAD

**Issue by mikeloveridge** [AScustomWorks/AS#46]
Hi!

This one took me a while to nail down what was happening.  I added a Phaser FX to one of my channels prior to my mixer and everything was great.  I added a second one to another channel and then it seemed I couldn't get my mix right.  It turns out the second Phaser seems to create a mix as if they were stereo Phasers with a separate channel going to left and one to right, but they are independent modules.

Not knowing how it's been implemented, it seems they are not separate instances from each other.  A second instance shares the inputs and outputs.  Hope this makes sense.  Let me know if you need me to put a sample patch together to demonstrate this.

Thanks!
Mike

P.S.  I don't know how to make a feature request so I'll just ask it here.  I'm often trying to figure out a way to incorporate the accents that some modules create.  What seems like something that should be simple isn't, but what would be nice is if a VCA had an Accent input as well as the normal CV from an envelope generator.  It could have a CV knob that lets you choose the amount of accent when it arrives.  Maybe I should just be summing the output of the EG with the accent signal, but that requires another module and more patching than if a VCA had an accent input.  Am I missing something simple when it comes to dealing with accents?  Thanks for reading!

**Comment by AScustomWorks** [comment]
Hi Mike!
Indeed, is a known bug on this module[phaserfx issue](https://github.com/AScustomWorks/AS/issues/30)
Somehow it seems that the phaser object is being set outside the module process, I've looked into it a couple of times now but haven't come with a solution yet, I'll review this issue again.

About the feature, just post a new issue, add "[Feature Request]" to the title and I can tag it as a request. Do that, and I'll follow up there please ;)

**Comment by AScustomWorks** [comment]
Fixed in both v1 and V2
