### ISSUE TITLE
AS v0.5.3 - 16-Step Sequencer (instead of "16 Steps")...

### ISSUE THREAD

**Issue by DomiKamu** [AScustomWorks/AS#5]
(Hello Alfredo)

...into its *SEQ16.svg* resource file (title is *near* correct from modules menu, but *16-Step Sequencer* would be... perfect!

Thanks a lot in advance.

Regards,
Dominique.

**Comment by DomiKamu** [comment]
Only modified **src/AS.cpp** and **res/SEQ.svg** in attached zip file.
[AS.zip](https://github.com/AScustomWorks/AS/files/1641891/AS.zip)

**Comment by AScustomWorks** [comment]
No problem doing this change, it will be available on the next release (0.5.4). btw, seeing your screenshot you are using the first release I think, and missing the new features ;)
