### ISSUE TITLE
Multiple Phasers affecting one another on different channels

### ISSUE THREAD

**Issue by AndrewC9** [AScustomWorks/AS#56]
When I'm using multiple phasers they seem to create a mix between them all even if they aren't on the same channel.

**Comment by jeremywen** [comment]
@AScustomWorks ya I just ran into this.  Add two green Phaser FX modules on two different mixer channels with different audio.  The audio will "bleed" into the other phaser.  Maybe like global variables or something?!?!

**Comment by AScustomWorks** [comment]
Hi Jeremy, I think it's the way the phaser class is declared, and where is declared but regular work has prevented me from taking a deeper look into this issue (and others) for months now :(
Now, I'm not as versed as I would want, to make the needed changes... do you think you could take a look to point me into the right direction? thanks!

**Comment by jeremywen** [comment]
I am not quite sure but could this line make a Phaser that is shared?  Should it be created in the contructor?  https://github.com/AScustomWorks/AS/blob/master/src/Phaser.cpp#L182

**Comment by AScustomWorks** [comment]
Somehow I don't get an e-mail about new posts here... I'll look into that, and into the Phaser fix... sorry for the massive delay :(.

**Comment by AScustomWorks** [comment]
And this one will be fixed on V2( and V1 too just to keep all tidy)

**Comment by AScustomWorks** [comment]
Fixed now
