### ISSUE TITLE
Clarifications on redistribution

### ISSUE THREAD

**Issue by falkTX** [AScustomWorks/AS#60]
Hi there.
I am interested on using your modules as part of another project, where the panel graphic files are used as-is (so it does not constitute derivative work).

Just want to clarify if this is all ok with you, or if you have special conditions for such a thing.
The project in question is https://github.com/DISTRHO/Cardinal

Basically I am repackaging your work, keeping all the code (from you and others) under GPLv3+ compatible licenses.
Thank you for your time.

**Comment by AScustomWorks** [comment]
Hi Filipe, thanks for asking.  Just one thing, to my understanding any use of the code and/or the graphics outside the original target (VCV Rack) constitutes a derivative work, even if nothing changes.

Even so, as long as there's no money involved in the use of your fork and the current graphics license disclaimer information is retained it's ok for you to use the AS free modules as they are (including all the graphics) as plugin for your Cardinal project, otherwise a graphics use license would need to be paid, or all the graphics should be replaced entirely altogether.

**Comment by falkTX** [comment]
Hi.

> Just one thing, to my understanding any use of the code and/or the graphics outside the original target (VCV Rack) constitutes a derivative work, even if nothing changes.

I think that needs to be explicitly stated. I didn't assume that to be case case, as literally all files are exactly the same. How is it a derivative if I changed nothing?
What if someone forks Rack just to be able to run it on an ARM system, does using your modules constitute derivative?
What if they change Rack a bit to work better for their needs, say adding/replacing things for blind users, would that be derivative?



> Even so, as long as there's no money involved in the use of your fork and the current graphics license disclaimer information is retained it's ok for you to use the AS free modules as they are (including all the graphics) as plugin for your Cardinal project, otherwise a graphics use license would need to be paid, or all the graphics should be replaced entirely altogether.

This is a problem too. There is money involved in Cardinal, indirectly, as I have a patreon account for donations.
I removed links to it on the Cardinal project out of caution, but it is easy to find elsewhere.
Honestly I would very much like to have a donation link directly on the Cardinal project, as it is a lot of work that is not compensated in any way, but stuff like this makes it very tricky and dangerous for me...

Related to money, it is also a problem for packaging in linux distributions, as they can easily be sold as part of something else (like a magazine) or sell itself as usb-stick for example.


As a final note, there is i also the topic of anyone forking Cardinal to make their own version (adding more modules for example). If you give permission for only Cardinal as-is to use your AS modules, it means any fork of Cardinal will need to ask permission again.
This just doesnt scale, and again hurts packaging on Linux distributions as they tend to need to patch things to better suit their distro system (thus basically maintaining a fork).

All of this sounds problematic to me, and I rather not take risks on licenses.
If you insist that usage outside of VCVRack, even though no files at all are changed, constitutes derivative - I will remove the modules from Cardinal. I think that is for the best, otherwise others would get into trouble because of me, assuming Cardinal to be an actual free, open-source project but then not being so.

Thanks and let me know what you think.

**Comment by falkTX** [comment]
Hi again.
Would be nice to have some conclusion here.

Since your idea is to not have derivatives or commercial use of your graphics, would you perhaps consider licensing them as CC-NC-ND? That would make it a lot better in terms of what is permitted and what is not.

I find your modules quite nice, it is a shame that they can't really be used right now unless the graphics are replaced.
The source code is quite permissive with its MIT license, so I am wondering about asking someone to redo the graphics in a more liberal license.. but at the same time using the official ones would be best.

**Comment by AScustomWorks** [comment]
Hi, I take only the free time I can find to get in here, sorry for the delay... and pushing is not polite, just saying.

Let's see it this way: You are abiding by the VCV Rack graphics copyright, right? , what makes my graphics and brand different?

I'm still thinking about this, but so far I can't see open source being the way.

**Comment by falkTX** [comment]
> Hi, I take only the free time I can find to get in here, sorry for the delay... and pushing is not polite, just saying.

I am sorry, didnt mean to be pushy. I see it just as having conversation and talking.
Not forcing you to respond here.

> Let's see it this way: You are abiding by the VCV Rack graphics copyright, right? , what makes my graphics and brand different?

I am not sure what you mean. I dont use any VCV trademarked graphics. The only stuff from Rack that gets used in Cardinal is the so called "Component Library" which is clearly licensed as [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)

Your graphics are quite different since they do not contain an actual license, but simply state the copyright and no derivative use allowed. (but give no rules in regards to redistribution for example)

> I'm still thinking about this, but so far I can't see open source being the way.

That would be sad to see, but completely your call.
Free software is cool for the resharing, the whole [free culture movement](https://en.wikipedia.org/wiki/Free-culture_movement). As long as the licenses are compatible we are free to reuse, remix, redistribute, resell and everything in between. I can use what is yours and you can use what is mine, we all work to benefit a commons. At least that is how I see it.

There are many licenses to pick from, from MIT/ISC/BSD ones that allow to do pretty much anything as long as the author is credited, to GPL that requires any change to be published back. There is no free software license that forbids commercial use, because that would restrict freedom of use (the free in free software is meant to be for freedom, not for gratis/zero-cost).

**Comment by AScustomWorks** [comment]
Sorry for the delay to answer, let's see:

The main issue I have is that the design of the component graphics and the panels design (with includes my own Brand logo both directly and as a watermark of sorts), is used (in parts or completely) on both the open source and paid plugins, which for obvious reasons works just fine for me... and that's the reason it gets complicated.

Btw. CC BY-NC-ND 4.0 sounds reasonable:

Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
NonCommercial — You may not use the material for commercial purposes.
NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

But, as you mentioned there is money involved with Cardinal so, what else can work?

Thanks for your patience on this matter.

**Comment by falkTX** [comment]
Thanks for getting back to this ticket.

Your points are all valid. Just a little thing..

> But, as you mentioned there is money involved with Cardinal so, what else can work?

There might be, or maybe not. Depends on the point of view and how stingy one wants to be. It is kinda grey area, and not a problem with just Cardinal.

For example, is using and showing off your modules on a monetized live stream breaking non-commercial clause? Someone is making money based on your work, perhaps indirectly, but your work is surely involved.
Another example, does publishing a news article behind a pay wall break the non-commercial clause? Imagine someone wants to write an extensive document about your modules, but wants some compensation for the amount of time spent on it.

I can come up with a few other cases, but I think you get the idea.
The non-commercial clause is just problematic in itself, and IMO it is a bad idea to release software with such conditions on it.
When someone thinks of opensource, they tend to think of having full access to it and being allowed to do anything with it too, it is all open in the end.

To come back to the topic, I have given up trying to move people away from CC-NC. There is just way too many Rack modules made with such licensing, and I cannot give any assurances or fix the issues around the reasons why CC-NC is used.
So we as Cardinal / VCV Rack users need to live with this grey area part of the software, where while artwork is CC-NC licensed we still use them in little commercial ways sometimes (look at those who made entire careers out of writing Rack related content and tutorials) and hope authors don't mind too much.

So with that said, if you relicense your artwork as CC BY-NC-ND 4.0 I will happily include them in Cardinal. And a few more users will be happy too, since they will have a few extra modules to use on their setups.

Thank you

**Comment by squinkylabs** [comment]
Forking and targeting to arm is for sure a derivative work. At least I believe most people would agree with that.

**Comment by falkTX** [comment]
is clone without changing any files still considered a fork? because then any packaging done by linux distros (which target many architectures besides just x64) would be not hold up anymore.

**Comment by Hoopeman** [comment]
Hello, since this module will not come out in cardinal, I recommend another one similar to FLOW (SWICH, DUAL, UTILITY) so that I can finish my construction! Thanks in advance.

**Comment by falkTX** [comment]
Sure, but you can continue the discussion already started in https://github.com/DISTRHO/Cardinal/discussions/63
No need to bother this repository / Alfredo for that.

**Comment by Hoopeman** [comment]
Okay! thank you

**Comment by AScustomWorks** [comment]
Hi, the graphics license is updated now to CC BY-NC-ND 4.0, (excluding the logo)indeed there's a grey area, but common sense should prevail if anything comes up.👍🏼

**Comment by falkTX** [comment]
That is very nice, thank you.
To be perfectly clear then, you wont mind me add your modules to Cardinal? They would go in the next 22.06 release

**Comment by AScustomWorks** [comment]
That's ok, go ahead.
