### ISSUE TITLE
AS v0.5.6 - Quad VCA/Mixer module : initial gain at 0 for all faders.

### ISSUE THREAD

**Issue by DomiKamu** [AScustomWorks/AS#8]
Hi Antonio,

Reporting a small - not critical - issue about faders in "QuadVCA/Mixer": initial gain for all four sliders are set to 0, instead of 50% like your other mixer modules (VCA and 8-CH Mixer).

On your todo list for next release (not crucial) :-) 
Bravo for your lastest Tremolo FX.

Regards.
Dominique Camus

**Comment by AScustomWorks** [comment]
Not really an issue as the module works as intended, it just happens to be the default setting ;)
